#!/usr/bin/env bash
#
# Rebuild the site and republish the `deploy` branch.
#
#   main    source — what you edit
#   deploy  the built site only — what the web server pulls
#
# The server's document root stays `httpdocs`, the same as every other site on the host,
# because `deploy` contains exactly what a browser needs and nothing else. That is the whole
# reason this script exists: keep the server ordinary, and do the awkward part here.
#
# Run from anywhere in the repository:  npm run publish
#
# It never touches your working tree — the branch is built in a temporary worktree.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

BRANCH="deploy"
WORKTREE="$(mktemp -d -t yourmove-deploy-XXXXXX)"

cleanup() {
  git worktree remove --force "$WORKTREE" >/dev/null 2>&1 || true
  rm -rf "$WORKTREE"
}
trap cleanup EXIT

if [ -n "$(git status --porcelain)" ]; then
  echo "Working tree is dirty. Commit or stash first, so the published site matches a commit." >&2
  exit 1
fi

echo "==> Checking the copy rules"
npm test

echo "==> Building"
rm -rf .next out
npm run build

# A published site that is missing its pages is worse than no publish at all.
for required in out/index.html out/profile/index.html out/legal/index.html \
                out/where-were-going/index.html out/signup.php; do
  [ -e "$required" ] || { echo "Build is incomplete: $required is missing." >&2; exit 1; }
done

echo "==> Updating the $BRANCH branch"
git fetch origin "$BRANCH" --quiet 2>/dev/null || true

if git show-ref --verify --quiet "refs/remotes/origin/$BRANCH"; then
  git worktree add --quiet "$WORKTREE" -B "$BRANCH" "origin/$BRANCH"
else
  git worktree add --quiet --detach "$WORKTREE"
  git -C "$WORKTREE" checkout --orphan "$BRANCH" --quiet
fi

# Replace the contents wholesale, so a page deleted in source disappears from the site too.
git -C "$WORKTREE" rm -rf --quiet . >/dev/null 2>&1 || true
cp -a "$ROOT/out/." "$WORKTREE/"
git -C "$WORKTREE" add -A

if git -C "$WORKTREE" diff --cached --quiet; then
  echo "==> The built site is unchanged. Nothing to publish."
  exit 0
fi

SOURCE_COMMIT="$(git rev-parse --short HEAD)"
git -C "$WORKTREE" commit --quiet -m "Built site from ${SOURCE_COMMIT}

Regenerated by scripts/publish.sh. Do not edit this branch by hand — the next publish
replaces it. Source, and the history worth reading, are on main."

echo "==> Pushing"
git -C "$WORKTREE" push --quiet origin "$BRANCH"

echo
echo "Published. In Plesk: Git -> Pull now, then Deploy now."
